baseURL = 'https://cesarbautista10.github.io/unit_blog_devlab/'
languageCode = 'es'
title = 'Documentación UNIT'

[params]
author = 'Equipo DevLab'
description = 'Documentación técnica, guías y recursos para tarjetas de desarrollo.'

# Giscus (GitHub Discussions)
[params.giscus]
repo          = "Cesarbautista10/unit_blog_devlab"
repo_id       = "R_kgDOSBrsnQ"
mapping       = "number"
term          = "1"
reactions     = "1"
emit_metadata = "0"
theme_light   = "light"
theme_dark    = "dark_dimmed"

[params.classification]
tipos = ['firmware', 'microcontroladores', 'productos', 'proximamente', 'caracteristicas-dispositivo', 'documentacion-general']
modulos = ['esp32', 'sensores', 'energia', 'pantallas', 'comunicacion', 'general']

[taxonomies]
tag = 'tags'
tipo = 'tipos'
modulo = 'modulos'
